version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste-csp
    working_dir: /teste-csp
    image: php:alpine
    volumes:
      - "./:/teste-csp"
    command: php artisan migrate
    command: php artisan serve
    ports:
      - 8000:8000
    network_mode: host
